{% set name = "streamlit-searchbox" %}
{% set version = "0.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit_searchbox-{{ version }}.tar.gz
  sha256: fb94290a46cfab4b7be41fb5703b20b4f2ef52d94cadc6e6068ffa9caa4eeed5
  patches:
    - 0001-remove-tests-from-distribution.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - streamlit >=1.10.0

test:
  imports:
    - streamlit_searchbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/m-wrzr/streamlit-searchbox
  summary: Autocomplete Searchbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ytausch
